version: '3.3'
services:
  mysql:
    image: mysql:5.7.24
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: very_secure_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql

  wordpress:
    image: apache-php:5.6
    build:
      context: apache-php
    restart: always
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql-data:
  wordpress:
